# Generated by Django 4.2.30 on 2026-06-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='samagra_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='scholar_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
