# Generated by Django 4.2.30 on 2026-07-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_samagra_id_student_scholar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='apar_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='APAR ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='student',
            name='board_enrollment_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Board Enrollment Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(blank=True, choices=[('SCIENCE', 'Science'), ('COMMERCE', 'Commerce'), ('BIOLOGY', 'Biology'), ('AGRICULTURE', 'Agriculture')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
