# Generated by Django 4.2.30 on 2026-06-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_date', models.DateField()),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit (Cash In)'), ('CREDIT', 'Credit (Cash Out)')], max_length=10)),
                ('category', models.CharField(choices=[('FEE_COLLECTION', 'Fee Collection'), ('SALARY', 'Salary Payment'), ('EXPENSE', 'Expense Payment'), ('INCOME', 'Non-fee Income'), ('MANUAL', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], default='CASH', max_length=10)),
                ('reference_id', models.CharField(blank=True, help_text='e.g. Receipt No, Payslip ID, Expense ID', max_length=100, null=True)),
                ('running_cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('running_bank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['entry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('INTERNET', 'Internet'), ('STATIONERY', 'Stationery'), ('FURNITURE', 'Furniture'), ('REPAIRS', 'Repairs'), ('MAINTENANCE', 'Maintenance'), ('WATER', 'Water'), ('TRANSPORT', 'Transport'), ('EVENTS', 'Events'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('before_state', models.TextField(blank=True, null=True)),
                ('after_state', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('DONATION', 'Donations'), ('UNIFORM_COMMISSION', 'Uniform Commission'), ('BOOK_COMMISSION', 'Book Commission'), ('EVENT_INCOME', 'Event Income'), ('MISCELLANEOUS', 'Miscellaneous Income')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-income_date', '-id'],
            },
        ),
    ]
