# Generated by Django 4.2.30 on 2026-06-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeestructure',
            name='student_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_dues', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='studentfeediscount',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_discounts', to='fees.feetype'),
        ),
        migrations.AddField(
            model_name='studentfeediscount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='students.student'),
        ),
        migrations.AddField(
            model_name='feecollectionitem',
            name='fee_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_items', to='fees.feecollection'),
        ),
        migrations.AddField(
            model_name='feecollectionitem',
            name='student_fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fees.studentfeestructure'),
        ),
    ]
