# Generated by Django 4.2.30 on 2026-06-08 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0002_initial'),
        ('students', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='student_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='classfeestructure',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fees', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='classfeestructure',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fees', to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='classfeestructure',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fees', to='fees.feetype'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfeediscount',
            unique_together={('student', 'fee_type')},
        ),
        migrations.AlterUniqueTogether(
            name='classfeestructure',
            unique_together={('academic_session', 'class_level', 'fee_type')},
        ),
    ]
